version: "3.8"

services:
  proxy:
    image: jupyterhub/configurable-http-proxy:4
    container_name: proxy
    networks:
      - jupyterhub-network
    # expose the proxy to the world, heal yeah
    ports:
      - "18081:8000"
    expose:
      - "8001"
    restart: unless-stopped
    env_file: .env
    environment:
      - CONFIGPROXY_AUTH_TOKEN=${CONFIGPROXY_AUTH_TOKEN}
    command:
      - configurable-http-proxy
      - "--ip=0.0.0.0"
      - "--port=8000"
      - "--api-ip=0.0.0.0"
      - "--api-port=8001"
      - "--error-target=http://hub:18000/hub/error"
      - "--log-level=info"
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:8000/hub/health"]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 3
  hub:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    image: jupyterhub
    container_name: jupyterhub
    networks:
      - jupyterhub-network
    volumes:
      # The JupyterHub configuration file
      - "./jupyterhub_config.py:/srv/jupyterhub/jupyterhub_config.py:ro"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "jupyterhub-data:/data"
      - "shared-data:/home/jovyan/shared"
    user: root
    command: jupyterhub --config /srv/jupyterhub/jupyterhub_config.py
    ports:
      - "18000:18000"
    env_file: .env
    depends_on:
      - proxy

volumes:
  jupyterhub-data:
  shared-data:

networks:
  jupyterhub-network:
    driver: bridge